apiVersion: v1
kind: Service
metadata:
  name: amf
  labels:
    app: amf
spec:
  selector:
    app: amf
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: amf
          image: 5gcore:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/5gcore-amf"]
          env:
            - name: NRF_URL
              value: "http://nrf:8000"
            - name: NF_HOST
              value: "amf"
            - name: NF_PORT
              value: "8001"
          ports:
            - containerPort: 8001
