apiVersion: v1
kind: Service
metadata:
  name: smf
  labels:
    app: smf
spec:
  selector:
    app: smf
  ports:
    - name: http
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: 5gcore:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/5gcore-smf"]
          env:
            - name: NRF_URL
              value: "http://nrf:8000"
            - name: NF_HOST
              value: "smf"
            - name: NF_PORT
              value: "8002"
          ports:
            - containerPort: 8002
